config/routes.rb
Gmaps::Application.routes.draw do  
  resources :users
    get 'auth/:provider/callback', to: 'sessions#create_integration'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
	
  get "sessions/new"
	get "sessions/create"
	get "sessions/destroy"
  get "sessions/login"
  get "sessions/home"
  get "sessions/profile"
  get "sessions/logout"
  
  post "sessions/login"
  post "sessions/home"
  post "users/show"
  
  get "comment/index"
  
  get 'home', to: 'home#index'
  get 'show_all', to: 'pois#index'
  get 'join_in', to: 'users#new'
  get 'all_images', to: 'home#all_images'
  get 'sign_in', to: 'sessions#login'
  get 'all_managers', to: 'home#all_managers'
  
  get '/application/request_role/:id', to: 'application#request_role', as: 'request_role'
  post '/application/request_role/:id', to: 'application#request_role'
  patch '/application/request_role/:id', to: 'application#request_role'
  
  get '/users/edit_role/:id', to: 'users#edit_role', as: 'edit_user_role'
  get '/users/update_role/:id', to: 'users#update_role'
  post '/users/update_role/:id', to: 'users#update_role'
  patch '/users/update_role/:id', to: 'users#update_role'
  
  get '/pois/:id/show_images', to: 'pois#show_images', as: 'show_images'
  
  get 'sessions/forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
  put 'sessions/forgot_password', to: 'sessions#send_password_reset_instructions'
  
  post "sessions/send_password_reset_instructions"
  
  get "password_reset" => "sessions#password_reset"
  put "password_reset" => "sessions#new_password"
  
  get '/comments/poi_comments/:id', to: 'comments#poi_comments', as: 'show_comments'
  
  get '/pois/about/:id', to: 'pois#edit'
  patch '/pois/about/:id', to: 'pois#edit'
  put '/pois/about/:id', to: 'pois#edit'
  
  post '/pois/:id', to: 'pois#update'
  patch '/pois/:id', to: 'pois#upload_image'
  put '/pois/:id', to: 'pois#upload_image'
  
  patch '/users/:id', to: 'users#upload_profile_image'
  put '/users/:id', to: 'users#upload_profile_image'
  
	get "home/index"
	get "pois/index"
	get "pois/show_all"
  get '/pois/show_users_pois', to: 'pois#show_users_pois', as: 'show_users_pois'
  
  get 'pois/delete_image/:file_name', to: 'pois#delete_image', as: 'delete_image'
  get 'users/delete_profile_image/:file_name', to: 'users#delete_profile_image', as: 'delete_profile_image'
  
  get 'comments/destroy/:id', to: 'comments#destroy', as: 'remove_comment'
  delete 'comments/destroy/:id/:poi_id', to: 'comments#destroy', as: 'delete_comment'
  
  get '/users/approve/:id', to: 'users#approve', as: 'approve'
  get '/users/disapprove/:id', to: 'users#disapprove', as: 'disapprove'
  
  get '/comments/comment_images/:id', to: 'comments#unapproved_images', as: 'show_unapproved_images'
  get '/comments/approved_images/:id', to: 'comments#approved_images', as: 'show_approved_images'
  
  get '/comments/:id/approve/image/:file_name', to: 'comments#approve_image', as: 'approve_image'
  get '/comments/:id/disapprove/image/:file_name', to: 'comments#disapprove_image', as: 'disapprove_image'
  get '/comments/:id/delete_approved/image/:file_name', to: 'comments#delete_approved_image', as: 'delete_approved_image'
	
	get '/comments/user_upload_image'
	post '/comments/user_upload_image', to: 'comments#user_upload_image'
	
	post '/pois/:id/new_title_image', to: 'pois#new_title_image'
	patch '/pois/:id/new_title_image', to: 'pois#new_title_image'
	
	
	
	
  get 'messages/index', to: 'messages#index', as: 'inbox'
  get 'messages/new', to: 'messages#new', as: 'new_message'
  
  get 'messages/create'
  post 'messages/create', to: 'messages#create'
  
  delete 'messages/destroy/:id', to: 'messages#destroy', as: 'delete_message'
  
  get 'messages/show/:id', to: 'messages#show', as: 'show_message'
  
  get 'messages/sent', to: 'messages#sent', as: 'sent'
  
  get 'pois/update_rating/:id/:rating', to: "pois#update_rating", as: 'update_rating'
  post 'pois/update_rating/:id/:rating', to: "pois#update_rating"
	
	resources :pois
      resources :sessions, only: [:create, :destroy]
    resources :comments
	
	root 'home#index'
end

app/models/message.rb
class Message < ActiveRecord::Base

  validates :recipient, presence: true
  validates :subject, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 240 }

end

app/controllers/messages_controller.rb
require 'fileutils'

class MessagesController < ApplicationController
  
  # Public: This gets all the messages and users for the index view to use.
  #
  def index
    @messages = Message.all
    @users = User.all
  end

  # Public: This gets all the users for the new view to use. It also creates a new
  # empty message to be able to send.
  #
  def new
    @users = User.all
    @message = Message.new
  end

  # Public: This gets the message by the id given from the url to show more information 
  # about the wanted message. It also gets all the users for the show view to use. It also 
  # updates the message's attribute has_read to true.
  #
  def show
    @message = Message.find(params[:id])
    @users = User.all
    @message.update_attribute(:has_read, true)
  end

  # Public: This gets all the messages and users for the sent view to use.
  #
  def sent
    @messages = Message.all
    @users = User.all
  end

  # Public: This creates and sends the new message to the correct user.
  #
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to inbox_path, notice: 'Message was successfully sent.' }
        format.json { render action: 'show', status: :created, location: inbox_path }
      else
        format.html { render action: 'new'}
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # Public: This destroies the given message by the id from the url.
  #
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to inbox_path
  end

  private
  
    def message_params
      params.require(:message).permit(:subject, :body, :sender, :recipient, :has_read)
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center><h2>Folders</h2></center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="inbox_messages">
		<center><h2><%= current_user.name %>'s Inbox</h2></center>
		<hr />
		<center>
			<% if @messages == nil %>
				<h3>You do not have anything in your inbox.</h3>
			<% else %>
			<table border="1">
				<thead>
					<tr>
						<th>From</th>
						<th>Subject</th>
						<th></th>
						<th></th>
					</tr>
			    </thead>
			    <tbody>
					<% @messages.each do |message| %>
						<% if message.recipient.to_s == current_user.id.to_s %>
							<tr>
								<% @users.each do |user| %>
									<% if message.sender.to_s == user.id.to_s %>
										<td><%= user.name %></td>
										<td><%= message.subject %></td>
									<% end %>
								<% end %>
								<td><%= link_to "View", show_message_path(message.id), 'data-no-turbolink' => true %></td>
								<td><%= link_to 'Destroy', delete_message_path(message.id), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
			<% end %>
		</center>
	</div>
</div>

app/views/messages/index.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center><h2>Folders</h2></center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="inbox_messages">
		<center><h2><%= current_user.name %>'s Inbox</h2></center>
		<hr />
		<center>
			<% if @messages == nil %>
				<h3>You do not have anything in your inbox.</h3>
			<% else %>
			<table border="1">
				<thead>
					<tr>
						<th>From</th>
						<th>Subject</th>
						<th></th>
						<th></th>
					</tr>
			    </thead>
			    <tbody>
					<% @messages.each do |message| %>
						<% if message.recipient.to_s == current_user.id.to_s %>
							<tr>
								<% @users.each do |user| %>
									<% if message.sender.to_s == user.id.to_s %>
										<td><%= user.name %></td>
										<td><%= message.subject %></td>
									<% end %>
								<% end %>
								<td><%= link_to "View", show_message_path(message.id), 'data-no-turbolink' => true %></td>
								<td><%= link_to 'Destroy', delete_message_path(message.id), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
			<% end %>
		</center>
	</div>
</div>

app/views/messages/new.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center>
			<h2>Folders</h2>
		</center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="new_message_content">
		<center>
			<h2>New Message</h2>
		</center>
		<hr />
		<center>
			<%= form_for(:message, :url => {:controller => 'messages', :action => 'create'}) do |f| %>
			<center>
				<table>
					<tr>
						<td><h2><label>From:</label></h2></td>
						<td><%= current_user.name %><%= f.hidden_field :sender, :value => current_user.id %></td>
					</tr>
					<tr>
						<td><h2><label>To:</label></h2></td>
						<td><%= select("message", "recipient", User.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }) %></td>
					</tr>
					<tr>
						<td><h2><label>Subject:</label></h2></td>
						<td><%= f.text_area :subject, :rows => 1, :cols => 55 %></td>
					</tr>
					<tr>
						<td><h2><label>Body:</label></h2></td>
						<td><%= f.text_area :body, :rows => 12, :cols => 55 %></td>
					</tr>
					<tr>
						<td><%= f.hidden_field :has_read, :value => "false" %></td>
						<td align="center"><%= f.submit 'Send Message' %></td>
					</tr>
				</table>
			</center>

			</br>
			<% if @message.errors.any? %>
			<center>
				<div id="error_explanation">
					<center>
						<h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>
					</center>
					<ul>
						<% @message.errors.full_messages.each do |msg| %>
						<li>
							<%= msg %>
						</li>
						<% end %>
					</ul>
				</div>
			</center>
			<% end %>

			<% end %>
		</center>
	</div>
</div>

app/views/messages/new.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center>
			<h2>Folders</h2>
		</center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="new_message_content">
		<center>
			<h2>New Message</h2>
		</center>
		<hr />
		<center>
			<%= form_for(:message, :url => {:controller => 'messages', :action => 'create'}) do |f| %>
			<center>
				<table>
					<tr>
						<td><h2><label>From:</label></h2></td>
						<td><%= current_user.name %><%= f.hidden_field :sender, :value => current_user.id %></td>
					</tr>
					<tr>
						<td><h2><label>To:</label></h2></td>
						<td><%= select("message", "recipient", User.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }) %></td>
					</tr>
					<tr>
						<td><h2><label>Subject:</label></h2></td>
						<td><%= f.text_area :subject, :rows => 1, :cols => 55 %></td>
					</tr>
					<tr>
						<td><h2><label>Body:</label></h2></td>
						<td><%= f.text_area :body, :rows => 12, :cols => 55 %></td>
					</tr>
					<tr>
						<td><%= f.hidden_field :has_read, :value => "false" %></td>
						<td align="center"><%= f.submit 'Send Message' %></td>
					</tr>
				</table>
			</center>

			</br>
			<% if @message.errors.any? %>
			<center>
				<div id="error_explanation">
					<center>
						<h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>
					</center>
					<ul>
						<% @message.errors.full_messages.each do |msg| %>
						<li>
							<%= msg %>
						</li>
						<% end %>
					</ul>
				</div>
			</center>
			<% end %>

			<% end %>
		</center>
	</div>
</div>

app/views/messages/sent.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center><h2>Folders</h2></center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="inbox_messages">
		<center><h2><%= current_user.name %>'s Sent Messages</h2></center>
		<hr />
		<center>
			<% if @messages == nil %>
				<h3>You do not have anything in your inbox.</h3>
			<% else %>
			<table border="1">
				<thead>
					<tr>
						<th></th>
						<th>To</th>
						<th>Subject</th>
						<th></th>
						<th></th>
					</tr>
			    </thead>
			    <tbody>
					<% @messages.each do |message| %>
						<% if message.sender.to_s == current_user.id.to_s %>
							<tr>
								<td></td>
								<% @users.each do |user| %>
									<% if user.id.to_s == message.recipient.to_s%>
										<td><%= user.name %></td>
									<% end %>
								<% end %>
								<td><%= message.subject %></td>
								<td><%= link_to "View", show_message_path(message.id), 'data-no-turbolink' => true %></td>
								<td><%= link_to 'Destroy', delete_message_path(message.id), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
			<% end %>
		</center>
	</div>
</div>

app/views/messages/sent.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center><h2>Folders</h2></center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="inbox_messages">
		<center><h2><%= current_user.name %>'s Sent Messages</h2></center>
		<hr />
		<center>
			<% if @messages == nil %>
				<h3>You do not have anything in your inbox.</h3>
			<% else %>
			<table border="1">
				<thead>
					<tr>
						<th></th>
						<th>To</th>
						<th>Subject</th>
						<th></th>
						<th></th>
					</tr>
			    </thead>
			    <tbody>
					<% @messages.each do |message| %>
						<% if message.sender.to_s == current_user.id.to_s %>
							<tr>
								<td></td>
								<% @users.each do |user| %>
									<% if user.id.to_s == message.recipient.to_s%>
										<td><%= user.name %></td>
									<% end %>
								<% end %>
								<td><%= message.subject %></td>
								<td><%= link_to "View", show_message_path(message.id), 'data-no-turbolink' => true %></td>
								<td><%= link_to 'Destroy', delete_message_path(message.id), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
			<% end %>
		</center>
	</div>
</div>

app/views/messages/show.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center><h2>Folders</h2></center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="show_message_content">
		<center><h2>Message</h2></center>
		<hr />
		<center>
			<table border="2">
		    	<tr>
					<% @users.each do |user| %>
						<% if user.id.to_s == @message.sender.to_s%>
							<th>From:</th>
							<td><%= user.name %></td>
						<% end %>
					<% end %>
				</tr>
				<tr>
					<th>Subject:</th>
					<td><%= @message.subject %></td>
				</tr>
				<tr>
					<th>Body:</th>
					<td><h3><%= @message.body %></h3></td>
				</tr>
			</table>
		</center>
	</div>
</div>

app/views/messages/show.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="inbox_content">
	<div id="inbox_folders">
		<center><h2>Folders</h2></center>
		<hr />
		<center>
			<table>
				<tr>
					<th><h3><%= link_to "Compose", new_message_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
				<tr>
					<th><h3><%= link_to "Sent", sent_path, 'data-no-turbolink' => true %></h3></th>
				</tr>
			</table>
		</center>
	</div>
	<div id="show_message_content">
		<center><h2>Message</h2></center>
		<hr />
		<center>
			<table border="2">
		    	<tr>
					<% @users.each do |user| %>
						<% if user.id.to_s == @message.sender.to_s%>
							<th>From:</th>
							<td><%= user.name %></td>
						<% end %>
					<% end %>
				</tr>
				<tr>
					<th>Subject:</th>
					<td><%= @message.subject %></td>
				</tr>
				<tr>
					<th>Body:</th>
					<td><h3><%= @message.body %></h3></td>
				</tr>
			</table>
		</center>
	</div>
</div>