config/routes.rb
Gmaps::Application.routes.draw do  
  resources :users
    get 'auth/:provider/callback', to: 'sessions#create_integration'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
	
  get "sessions/new"
	get "sessions/create"
	get "sessions/destroy"
  get "sessions/login"
  get "sessions/home"
  get "sessions/profile"
  get "sessions/logout"
  
  post "sessions/login"
  post "sessions/home"
  post "users/show"
  
  get "comment/index"
  
  get 'home', to: 'home#index'
  get 'show_all', to: 'pois#index'
  get 'join_in', to: 'users#new'
  get 'all_images', to: 'home#all_images'
  get 'sign_in', to: 'sessions#login'
  get 'all_managers', to: 'home#all_managers'
  
  get '/application/request_role/:id', to: 'application#request_role', as: 'request_role'
  post '/application/request_role/:id', to: 'application#request_role'
  patch '/application/request_role/:id', to: 'application#request_role'
  
  get '/users/edit_role/:id', to: 'users#edit_role', as: 'edit_user_role'
  get '/users/update_role/:id', to: 'users#update_role'
  post '/users/update_role/:id', to: 'users#update_role'
  patch '/users/update_role/:id', to: 'users#update_role'
  
  get '/pois/:id/show_images', to: 'pois#show_images', as: 'show_images'
  
  get 'sessions/forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
  put 'sessions/forgot_password', to: 'sessions#send_password_reset_instructions'
  
  post "sessions/send_password_reset_instructions"
  
  get "password_reset" => "sessions#password_reset"
  put "password_reset" => "sessions#new_password"
  
  get '/comments/poi_comments/:id', to: 'comments#poi_comments', as: 'show_comments'
  
  get '/pois/about/:id', to: 'pois#edit'
  patch '/pois/about/:id', to: 'pois#edit'
  put '/pois/about/:id', to: 'pois#edit'
  
  post '/pois/:id', to: 'pois#update'
  patch '/pois/:id', to: 'pois#upload_image'
  put '/pois/:id', to: 'pois#upload_image'
  
  patch '/users/:id', to: 'users#upload_profile_image'
  put '/users/:id', to: 'users#upload_profile_image'
  
	get "home/index"
	get "pois/index"
	get "pois/show_all"
  get '/pois/show_users_pois', to: 'pois#show_users_pois', as: 'show_users_pois'
  
  get 'pois/delete_image/:file_name', to: 'pois#delete_image', as: 'delete_image'
  get 'users/delete_profile_image/:file_name', to: 'users#delete_profile_image', as: 'delete_profile_image'
  
  get 'comments/destroy/:id', to: 'comments#destroy', as: 'remove_comment'
  delete 'comments/destroy/:id/:poi_id', to: 'comments#destroy', as: 'delete_comment'
  
  get '/users/approve/:id', to: 'users#approve', as: 'approve'
  get '/users/disapprove/:id', to: 'users#disapprove', as: 'disapprove'
  
  get '/comments/comment_images/:id', to: 'comments#unapproved_images', as: 'show_unapproved_images'
  get '/comments/approved_images/:id', to: 'comments#approved_images', as: 'show_approved_images'
  
  get '/comments/:id/approve/image/:file_name', to: 'comments#approve_image', as: 'approve_image'
  get '/comments/:id/disapprove/image/:file_name', to: 'comments#disapprove_image', as: 'disapprove_image'
  get '/comments/:id/delete_approved/image/:file_name', to: 'comments#delete_approved_image', as: 'delete_approved_image'
	
	get '/comments/user_upload_image'
	post '/comments/user_upload_image', to: 'comments#user_upload_image'
	
	post '/pois/:id/new_title_image', to: 'pois#new_title_image'
	patch '/pois/:id/new_title_image', to: 'pois#new_title_image'
	
	
	
	
  get 'messages/index', to: 'messages#index', as: 'inbox'
  get 'messages/new', to: 'messages#new', as: 'new_message'
  
  get 'messages/create'
  post 'messages/create', to: 'messages#create'
  
  delete 'messages/destroy/:id', to: 'messages#destroy', as: 'delete_message'
  
  get 'messages/show/:id', to: 'messages#show', as: 'show_message'
  
  get 'messages/sent', to: 'messages#sent', as: 'sent'
  
  get 'pois/update_rating/:id/:rating', to: "pois#update_rating", as: 'update_rating'
  post 'pois/update_rating/:id/:rating', to: "pois#update_rating"
	
	resources :pois
      resources :sessions, only: [:create, :destroy]
    resources :comments
	
	root 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  validates :text, presence: true, length: { maximum: 240 }
  
  cattr_accessor :comment_image
  @@comment_image = false
end

app/controllers/comments_controller.rb
require 'fileutils'

class CommentsController < ApplicationController
  
  # Public: This gets all the POI's and comments for the index view to use.
  #
  def index
    @poi = Poi.all
    @comment = Comment.all
  end
  
  # Public: This gets the POI that is passed in by the url and it gets all the
  # users for the poi_comments view to use.
  #
  def poi_comments
    @poi = Poi.find(params[:id])
    @users = User.all
  end
  
  # Public: This gets all the information needed to create a new comment for the
  # POI's id, passed in by the url. If the user added an image, it will upload that
  # image to the disapproved image folder of that POI. It also sends the admin a email
  # saying that someone has uploaded an image to that POI.
  #
  def create
    @poi = Poi.find(params[:comment][:poi_id])
    @admin = User.find_by_roles("Admin")
    @comment = @poi.comments.create(comment_params)
    
    path_name = "#{Rails.root}/public/images/#{@poi.id}_images/user_images/disapproved"
    file_name = "#{@comment.id}"
    
    if params[:comment]['file'] != nil
      UserMailer.image_approve(@poi, @admin).deliver
      Poi.super_without_name(params[:comment], file_name, path_name)
    end
    
    redirect_to poi_path(@poi)
  end
  
  # Public: This will upload the given image to the disapproved image folder of that POI, 
  # that is passed in by the url. It also sends the admin a email
  # saying that someone has uploaded an image to that POI.
  #
  def user_upload_image
    @poi = Poi.find(params[:comment][:poi_id])
    @admin = User.find_by_roles("Admin")
    path_name = "#{Rails.root}/public/images/#{@poi.id}_images/user_images/disapproved"
    
    if params[:comment]['file'] != nil
      UserMailer.image_approve(@poi, @admin).deliver
      Poi.super_with_name(params[:comment], "", path_name)
    end
    
    redirect_to poi_path(@poi)
  end
  
  # Public: This destroies the given comment by the comment id, given by 
  # the url.
  #
  def destroy
    @poi = Poi.find(params[:poi_id])
    @comment = @poi.comments.find(params[:id])
    @comment.destroy
    redirect_to show_comments_path(@poi)
  end
  
  # Public: This allows the upapproved_images view to find the POI with the 
  # given id, given by the url.
  #
  def unapproved_images
    @poi = Poi.find(params[:id])
  end
  
  # Public: This allows the approved_images view to find the POI with the 
  # given id, given by the url.
  #
  def approved_images
    @poi = Poi.find(params[:id])
  end
  
  # Public: This moves the given image, image that was uploaded by a user as a comment,
  # to the approved images folder from the poi, given the id by the url.
  #
  def approve_image
    @poi = Poi.find(params[:id])
    
    ext = "." + "#{params[:format]}"
    file_name_old = "#{Rails.root}/public/images/#{params[:id]}_images/user_images/disapproved/#{params[:file_name]}#{ext}"
    file_name_new = "#{Rails.root}/public/images/#{params[:id]}_images/user_images/approved/#{params[:file_name]}#{ext}"
    FileUtils.mv(file_name_old, file_name_new) if File.file?(file_name_old)
    
    redirect_to show_unapproved_images_path(@poi), notice: ' Image was successfully approved.'
  end
  
  # Public: This deletes the given image, image that was uploaded by a user as a comment,
  # from the poi, given the id by the url.
  #
  def disapprove_image
    @poi = Poi.find(params[:id])
    
    ext = "." + "#{params[:format]}"
    file_name = "#{Rails.root}/public/images/#{params[:id]}_images/user_images/disapproved/#{params[:file_name]}#{ext}"
    File.delete(file_name) if File.file?(file_name)
    
    redirect_to show_unapproved_images_path(@poi), notice: ' Image was not approved so was removed.'
  end
  
  # Public: This deletes the given image, image that was approved by an admin as a comment,
  # from the poi, given the id by the url.
  #
  def delete_approved_image
    @poi = Poi.find(params[:id])
    
    ext = "." + "#{params[:format]}"
    file_name = "#{Rails.root}/public/images/#{params[:id]}_images/user_images/approved/#{params[:file_name]}#{ext}"
    File.delete(file_name) if File.file?(file_name)
    
    redirect_to show_approved_images_path(@poi), notice: ' Image was successfully removed.'
  end
  
  private

    def comment_params
      params.require(:comment).permit(:user_id, :poi_id, :text)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
<%= comment.user_id %>
</p>
<p>
<%= comment.poi_id %>
</p>
<p>
<%= comment.text %>
</p>
<p>
<%= link_to 'Destroy Comment', [@poi, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/approved_images.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="content">
	<center>
		<div id="each_comment_table">
			<h2>All Approved User Images For Wolf: <%= @poi.title %></h2>
			<table border="1">
				<thead>
					<tr>
						<th>Image</th>
						<th></th>
					</tr>
				</thead>
				
				<tbody>
					<% Dir.entries("public/images/#{@poi.id}_images/user_images/approved")[2..-1].each do |file_name| %>
					<tr>
						<td><%= image_tag("#{@root_url}/images/#{@poi.id}_images/user_images/approved/" + file_name) %></td>
						<td><%= link_to 'Delete Image', delete_approved_image_path(@poi, file_name), data: {confirm: 'Are you sure you want to deleted this approved image?' }, 'data-no-turbolink' => true %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</center>
</div>

app/views/comments/approved_images.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="content">
	<center>
		<div id="each_comment_table">
			<h2>All Approved User Images For Wolf: <%= @poi.title %></h2>
			<table border="1">
				<thead>
					<tr>
						<th>Image</th>
						<th></th>
					</tr>
				</thead>
				
				<tbody>
					<% Dir.entries("public/images/#{@poi.id}_images/user_images/approved")[2..-1].each do |file_name| %>
					<tr>
						<td><%= image_tag("#{@root_url}/images/#{@poi.id}_images/user_images/approved/" + file_name) %></td>
						<td><%= link_to 'Delete Image', delete_approved_image_path(@poi, file_name), data: {confirm: 'Are you sure you want to deleted this approved image?' }, 'data-no-turbolink' => true %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</center>
</div>

app/views/comments/poi_comments.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="content">
	<center>
		<div id="each_comment_table">
			<h2>All Comments About Wolf: <%= @poi.title %></h2>
			<table border="1">
				<thead>
					<tr>
						<th>User Name</th>
						<th>Comment</th>
						<% if current_user.roles == "Admin" %>
							<th></th>
						<% end %>
					</tr>
				</thead>
				
				<tbody>
					<% @poi.comments.each do |comment| %>
						<% @users.each do |user| %>
							<% if user.id.to_s == comment.user_id.to_s %>
								<tr>
									<td><%= user.name %></td>
									<td><%= comment.text %></td>
									<% if current_user.roles == "Admin" %>
										<td><%= link_to 'Destroy', delete_comment_path(comment, @poi.id), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
									<% end %>
								</tr>
							<% end %>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</center>
</div>

app/views/comments/poi_comments.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="content">
	<center>
		<div id="each_comment_table">
			<h2>All Comments About Wolf: <%= @poi.title %></h2>
			<table border="1">
				<thead>
					<tr>
						<th>User Name</th>
						<th>Comment</th>
						<% if current_user.roles == "Admin" %>
							<th></th>
						<% end %>
					</tr>
				</thead>
				
				<tbody>
					<% @poi.comments.each do |comment| %>
						<% @users.each do |user| %>
							<% if user.id.to_s == comment.user_id.to_s %>
								<tr>
									<td><%= user.name %></td>
									<td><%= comment.text %></td>
									<% if current_user.roles == "Admin" %>
										<td><%= link_to 'Destroy', delete_comment_path(comment, @poi.id), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
									<% end %>
								</tr>
							<% end %>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</center>
</div>

app/views/comments/unapproved_images.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="content">
	<center>
		<div id="each_comment_table">
			<h2>All Images Needing Approving For Wolf: <%= @poi.title %></h2>
			<table border="1">
				<thead>
					<tr>
						<th>Image</th>
						<th></th>
					</tr>
				</thead>
				
				<tbody>
					<% Dir.entries("public/images/#{@poi.id}_images/user_images/disapproved")[2..-1].each do |file_name| %>
						<tr>
							<td><%= image_tag("#{@root_url}/images/#{@poi.id}_images/user_images/disapproved/" + file_name) %></td>
							<td>
								<%= link_to 'Approve Image', approve_image_path(@poi, file_name), data: {confirm: 'Are you sure you want to approve this image?' }, 'data-no-turbolink' => true %><br />
								<%= link_to 'Disapprove Image', disapprove_image_path(@poi, file_name), data: {confirm: 'Are you sure you want to disapprove this image? It will be deleted if so.' }, 'data-no-turbolink' => true %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</center>
</div>

app/views/comments/unapproved_images.mobile.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="content">
	<center>
		<div id="each_comment_table">
			<h2>All Images Needing Approving For Wolf: <%= @poi.title %></h2>
			<table border="1">
				<thead>
					<tr>
						<th>Image</th>
						<th></th>
					</tr>
				</thead>
				
				<tbody>
					<% Dir.entries("public/images/#{@poi.id}_images/user_images/disapproved")[2..-1].each do |file_name| %>
						<tr>
							<td><%= image_tag("#{@root_url}/images/#{@poi.id}_images/user_images/disapproved/" + file_name) %></td>
							<td>
								<%= link_to 'Approve Image', approve_image_path(@poi, file_name), data: {confirm: 'Are you sure you want to approve this image?' }, 'data-no-turbolink' => true %><br />
								<%= link_to 'Disapprove Image', disapprove_image_path(@poi, file_name), data: {confirm: 'Are you sure you want to disapprove this image? It will be deleted if so.' }, 'data-no-turbolink' => true %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</center>
</div>