config/routes.rb
Gmaps::Application.routes.draw do  
  resources :users
    get 'auth/:provider/callback', to: 'sessions#create_integration'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
	
  get "sessions/new"
	get "sessions/create"
	get "sessions/destroy"
  get "sessions/login"
  get "sessions/home"
  get "sessions/profile"
  get "sessions/logout"
  
  post "sessions/login"
  post "sessions/home"
  post "users/show"
  
  get "comment/index"
  
  get 'home', to: 'home#index'
  get 'show_all', to: 'pois#index'
  get 'join_in', to: 'users#new'
  get 'all_images', to: 'home#all_images'
  get 'sign_in', to: 'sessions#login'
  get 'all_managers', to: 'home#all_managers'
  
  get '/application/request_role/:id', to: 'application#request_role', as: 'request_role'
  post '/application/request_role/:id', to: 'application#request_role'
  patch '/application/request_role/:id', to: 'application#request_role'
  
  get '/users/edit_role/:id', to: 'users#edit_role', as: 'edit_user_role'
  get '/users/update_role/:id', to: 'users#update_role'
  post '/users/update_role/:id', to: 'users#update_role'
  patch '/users/update_role/:id', to: 'users#update_role'
  
  get '/pois/:id/show_images', to: 'pois#show_images', as: 'show_images'
  
  get 'sessions/forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
  put 'sessions/forgot_password', to: 'sessions#send_password_reset_instructions'
  
  post "sessions/send_password_reset_instructions"
  
  get "password_reset" => "sessions#password_reset"
  put "password_reset" => "sessions#new_password"
  
  get '/comments/poi_comments/:id', to: 'comments#poi_comments', as: 'show_comments'
  
  get '/pois/about/:id', to: 'pois#edit'
  patch '/pois/about/:id', to: 'pois#edit'
  put '/pois/about/:id', to: 'pois#edit'
  
  post '/pois/:id', to: 'pois#update'
  patch '/pois/:id', to: 'pois#upload_image'
  put '/pois/:id', to: 'pois#upload_image'
  
  patch '/users/:id', to: 'users#upload_profile_image'
  put '/users/:id', to: 'users#upload_profile_image'
  
	get "home/index"
	get "pois/index"
	get "pois/show_all"
  get '/pois/show_users_pois', to: 'pois#show_users_pois', as: 'show_users_pois'
  
  get 'pois/delete_image/:file_name', to: 'pois#delete_image', as: 'delete_image'
  get 'users/delete_profile_image/:file_name', to: 'users#delete_profile_image', as: 'delete_profile_image'
  
  get 'comments/destroy/:id', to: 'comments#destroy', as: 'remove_comment'
  delete 'comments/destroy/:id/:poi_id', to: 'comments#destroy', as: 'delete_comment'
  
  get '/users/approve/:id', to: 'users#approve', as: 'approve'
  get '/users/disapprove/:id', to: 'users#disapprove', as: 'disapprove'
  
  get '/comments/comment_images/:id', to: 'comments#unapproved_images', as: 'show_unapproved_images'
  get '/comments/approved_images/:id', to: 'comments#approved_images', as: 'show_approved_images'
  
  get '/comments/:id/approve/image/:file_name', to: 'comments#approve_image', as: 'approve_image'
  get '/comments/:id/disapprove/image/:file_name', to: 'comments#disapprove_image', as: 'disapprove_image'
  get '/comments/:id/delete_approved/image/:file_name', to: 'comments#delete_approved_image', as: 'delete_approved_image'
	
	get '/comments/user_upload_image'
	post '/comments/user_upload_image', to: 'comments#user_upload_image'
	
	post '/pois/:id/new_title_image', to: 'pois#new_title_image'
	patch '/pois/:id/new_title_image', to: 'pois#new_title_image'
	
	
	
	
  get 'messages/index', to: 'messages#index', as: 'inbox'
  get 'messages/new', to: 'messages#new', as: 'new_message'
  
  get 'messages/create'
  post 'messages/create', to: 'messages#create'
  
  delete 'messages/destroy/:id', to: 'messages#destroy', as: 'delete_message'
  
  get 'messages/show/:id', to: 'messages#show', as: 'show_message'
  
  get 'messages/sent', to: 'messages#sent', as: 'sent'
  
  get 'pois/update_rating/:id/:rating', to: "pois#update_rating", as: 'update_rating'
  post 'pois/update_rating/:id/:rating', to: "pois#update_rating"
	
	resources :pois
      resources :sessions, only: [:create, :destroy]
    resources :comments
	
	root 'home#index'
end

app/models/poi.rb
class Poi < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  geocoded_by :address
  after_validation :geocode
  attr_accessor :img

  validates :title, presence: true, length: { maximum: 50 }
  validates :sponsor, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 240 }
  validate :address
  
  validate :check_address_or_lat_long

  cattr_accessor :poi_home_image
  cattr_accessor :poi_counter
  
  @@poi_home_image = false
  @@poi_counter = 0
  
  # Public: This checks to see if either the user filled out the lat and long or the
  # address of the new POI. 
  #
  # * *Returns* :
  #   - true is the address or lat and long are filled out.
  #
  def check_address_or_lat_long
    if address.blank? and latitude.blank? and longitude.blank?
      return false
    elsif !address.blank? and latitude.blank? and longitude.blank?
      return true
    elsif address.blank? and !latitude.blank? and !longitude.blank?
      return true
    elsif !address.blank? and !latitude.blank? and !longitude.blank?
      return false
    end
  end

  # Public: This will take the image uploaded and give it just the name of the file name passed in
  # and save it to the path name that was given.
  #
  # * *Args*    :
  #   - +upload+ -> This is the object that holds the image that was uploaded.
  #   - +file_name+ -> This is the file name that the file is going to have.
  #   - +path_name+ ->  This is the path name of the file to be put in.
  #
  def self.super_without_name(upload, file_name, path_name)
    name = file_name
    path = File.join(path_name,name)
    File.open(path, 'wb') do |file|
      file.write(upload[:file].read)
    end
  end

  # Public: This will take the image uploaded with its name appended with the file name passed 
  # in infront of it and save it to the path name that was given.
  #
  # * *Args*    :
  #   - +upload+ -> This is the object that holds the image that was uploaded.
  #   - +file_name+ -> This is the file name that the file is going to have.
  #   - +path_name+ ->  This is the path name of the file to be put in.
  #
  def self.super_with_name(upload, file_name, path_name)
    name = file_name + upload[:file].original_filename.downcase
    path = File.join(path_name,name)
    File.open(path, 'wb') do |file|
      file.write(upload[:file].read)
    end
  end

end

app/controllers/pois_controller.rb
require 'fileutils'

class PoisController < ApplicationController
  before_action :set_poi, only: [:show, :edit, :update, :destroy, :show_images]

  
  # Public: This gets all the POI's and users for the index view to use. It also creates
  # a hash that has all the information about each of the POI's to show on the map.
  #
  def index
    @poi = Poi.all
    @users = User.all
    @hash = Gmaps4rails.build_markers(@poi) do |poi, marker|
      next if poi.latitude.nil? || poi.longitude.nil?
      marker.lat poi.latitude
      marker.lng poi.longitude
      marker.title poi.title
    end
  end

  # Public: This gets the POI by the given id from the url. It also creates
  # a hash to only has the POI's that the current_users created.
  #
  def show_users_pois
    @poi = Poi.where("user_id == #{current_user.id}")
    @hash = Gmaps4rails.build_markers(@poi) do |poi, marker|
      next if poi.latitude.nil? || poi.longitude.nil?
      marker.lat poi.latitude
      marker.lng poi.longitude
      marker.title poi.title
    end
  end

  # Public: This gets all the users for the show view to use.
  #
  def show
    @users = User.all
  end

  # Public: This gets the POI given the id from the url to be able to go into
  # that POI's images folder to view all the managers uploaded images.
  #
  def show_images
    @poi = Poi.find(params[:id])
  end

  # Public: This creates an empty POI to be able to create a new one given.
  #
  def new
    @poi = Poi.new
  end

  # Public: This creates a POI given all the information filled out. It also creates many new
  # folders for the new POI. It creates an image folder named "poi.id_images". With in that,
  # it creates "user_images" and "title_image" folders. Then within the "user_images" folders,
  # it creates 2 more folders named "approved" and "disapproved". If the user uploaded an image
  # when creating the POI, it makes that image the title image and puts it in the "title_image"
  # folder. 
  #
  def create
    @poi = Poi.new(poi_params)

    respond_to do |format|
      if @poi.save
        path_name = "#{Rails.root}/public/images/#{@poi.id}_images/"
        path_name_user = "#{Rails.root}/public/images/#{@poi.id}_images/user_images/"
        path_name_title_image = "#{Rails.root}/public/images/#{@poi.id}_images/title_image/"
        
        path_image_approve = "#{Rails.root}/public/images/#{@poi.id}_images/user_images/approved"
        path_image_disapprove = "#{Rails.root}/public/images/#{@poi.id}_images/user_images/disapproved"
        
        FileUtils.mkdir_p(path_name)
        FileUtils.mkdir_p(path_name_user)
        FileUtils.mkdir_p(path_name_title_image)
        
        FileUtils.mkdir_p(path_image_approve)
        FileUtils.mkdir_p(path_image_disapprove)

        if params[:poi]['file'] != nil
          Poi.super_with_name(params[:poi], "_poi_", path_name_title_image)

          format.html { redirect_to show_images_path(@poi.id), notice: 'Poi was successfully created. Now upload all your other images here.' }
          format.json { render action: 'show', status: :created, location: @poi }
        else
          format.html { redirect_to show_images_path(@poi.id), notice: 'Poi was successfully created. Now upload all your other images here.' }
          format.json { render action: 'show', status: :created, location: @poi }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # Public: This updates the given POI with all the new information.
  #
  def update
    respond_to do |format|
      if @poi.update(poi_params)
        format.html { redirect_to @poi, notice: " #{@poi.title} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # Public: This uploades the image given to the given POI, found by the id in the url.
  #
  def upload_image
    respond_to do |format|
      if params[:poi]['file'] != nil
        poi_id = params[:poi]['poi_id']
        path_name = "#{Rails.root}/public/images/#{poi_id}_images/"

        FileUtils.mkdir_p(path_name) if !File.exist?(path_name)
        Poi.super_with_name(params[:poi], "_poi_", path_name)

        format.html { redirect_to show_images_path(poi_id), notice: ' Image was successfully added.' }
        format.json { head :no_content }
      else
        update
      end
    end
  end

  # Public: This destroies the POI given by the id in the url. It also deletes the
  # "poi.id_images" folder, so in turn deletes all of its sub folders.
  #
  def destroy
    @poi.destroy
    FileUtils.remove_dir "#{Rails.root}/public/images/#{@poi.id}_images"
    respond_to do |format|
      format.html { redirect_to show_all_path }
      format.json { head :no_content }
    end
  end

  # Public: This deletes the wanted image.
  #
  def delete_image
    ext = "." + "#{params[:format]}"
    file_name = "#{Rails.root}/public/images/#{params[:poi_id]}_images/#{params[:file_name]}#{ext}"
    File.delete(file_name) if File.file?(file_name)
    redirect_to show_images_path(params[:poi_id])
  end
  
  # Public: This moves the old title image to the "poi.id_images" folder and moves the new wanted 
  # image to the "title_image" folder.
  #
  def new_title_image
    if params[:title_image] != nil
      # Moves the old image to the image folder
      old_title_image_path = "#{Rails.root}/public/images/#{params[:id]}_images/title_image/#{params[:poi]['current_title_image']}"
      old_title_image_new_path = "#{Rails.root}/public/images/#{params[:id]}_images/#{params[:poi]['current_title_image']}"
      FileUtils.mv(old_title_image_path, old_title_image_new_path)
      
      # Moves the wanted image to the title image folder
      new_title_image_path = "#{Rails.root}/public/images/#{params[:id]}_images/#{params[:title_image]}"
      new_title_image_new_path = "#{Rails.root}/public/images/#{params[:id]}_images/title_image/#{params[:title_image]}"
      FileUtils.mv(new_title_image_path, new_title_image_new_path)
    end
    
    redirect_to show_images_path(params[:id])
  end
  
  # Public: This updates the rating information of the given POI by the id in 
  # the url. 
  #
  def update_rating
    @poi = Poi.find(params[:id])
    total_ratings = @poi.total_ratings.to_i + params[:rating].to_i
    number_people = @poi.total_people.to_i + 1
    new_avg = total_ratings.to_i / number_people.to_i
    
    @poi.update_attribute(:total_ratings, total_ratings.to_i)
    @poi.update_attribute(:total_people, number_people.to_i)
    @poi.update_attribute(:avg_rating, new_avg.to_i)
    
    redirect_to @poi
  end

  private

    def set_poi
      @poi = Poi.find(params[:id])
    end
  
    def poi_params
      params.require(:poi).permit(:title, :address, :sponsor, :description, :latitude, :longitude, :user_id)
    end
    
    def poi_rating_params
      params.require(:poi).permit(:total_people)
    end
    
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/views/pois/all_comments.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div id="wrapper">
	<div id="header">
		<center><h1>All Comments</h1></center>
	</div>
	<center><div id="nav">
		<ul>
			<li class="float_left"><%= link_to "Home", home_path %></li>
			<li class="float_center"><%= link_to "Summary", summary_path %></li>
			<li class="float_right"><%= link_to "Show_All", show_all_path %></li>
		</ul>
	</div></center>
	<div id="content">	
		<center>
			<h2>List of all the comments on all pois</h2>
		</center>
		<hr>
		<center>
			<table border="2">
				<thead>
					<tr>
						<th>User Id</th>
						<th>POI Id</th>
						<th>Comment Text</th>
						<th></th>
					</tr>
			    </thead>

				<tbody>
				<% @comment.each do |comment| %>
					<tr>
						<td><%= comment.user_id %></td>
						<td><%= comment.poi_id %></td>
						<td><%= comment.text %></td>
						
						<td><%= link_to 'Destroy Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</center>
	</div>
</div>

app/views/pois/all_comments.mobile.erb
<%= stylesheet_link_tag "#{params[:controller]}.mobile" %>

<div id="wrapper">
	<div id="header">
		<center><h1>All Comments</h1></center>
	</div>
	<center><div id="nav">
		<ul>
			<li class="float_left"><%= link_to "Home", home_path %></li>
			<li class="float_center"><%= link_to "Summary", summary_path %></li>
			<li class="float_right"><%= link_to "Show_All", show_all_path %></li>
		</ul>
	</div></center>
	<div id="content">	
		<center>
			<h2>List of all the comments on all pois</h2>
		</center>
		<hr>
		<center>
			<table border="2">
				<thead>
					<tr>
						<th>User Id</th>
						<th>POI Id</th>
						<th>Comment Text</th>
						<th></th>
					</tr>
			    </thead>

				<tbody>
				<% @comment.each do |comment| %>
					<tr>
						<td><%= comment.user_id %></td>
						<td><%= comment.poi_id %></td>
						<td><%= comment.text %></td>
						
						<td><%= link_to 'Destroy Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</center>
	</div>
</div>

app/views/pois/index.html.erb
<%= stylesheet_link_tag params[:controller] %>
	
<div id="content_show_all">	
	<div id="all_list">
		<center>
			<h2>Here are all the Wolves!</h2>
		</center>
		<hr>
		<center>
			<table border="2">
				<thead>
					<tr>
						<th>Image</th>
						<th>Title</th>
						<th>Artist Name</th>
						<th>Address</th>
						<th>Description</th>
						<th>Show</th>
						<% if current_user != nil %>
							<% if current_user.roles == "Admin" %>
								<th>User</th>
								<th>Unapproved</th>
								<th>Approved</th>
							<% end %>
						<% end %>
						<th>Go Here</th>
					</tr>
			    </thead>
	
				<tbody>
				<% @poi.each do |poi| %>
					<tr>
						<% Poi.poi_home_image = false %>
						<% Dir.entries("public/images/#{poi.id}_images/title_image")[2..-1].each do |file_name| %>
							<% if file_name.byteslice(0,5).to_s.match(/_poi_/) %>
								<td><%= image_tag("#{@root_url}/images/#{poi.id}_images/title_image/" + file_name) %></td>
								<% Poi.poi_home_image = true %>
							<% end %>
						<% end %>
						
						<% if Poi.poi_home_image == false %>
							<td><img src="<%= @root_url %>/profile_images/no_profile_image.jpg" /></td>
						<% end %>
						
						<td><%= poi.title %></td>
						
						<% @users.each do |user| %>
							<% if user.id.to_s == poi.user_id.to_s %>
								<td><%= user.name %></td>
							<% end %>
						<% end %>
						
						<td><%= poi.address %></td>
						<td><%= truncate(poi.description, :length => 50) %></td>
						<td><%= link_to "View", "/pois/#{poi.id}", 'data-no-turbolink' => true %></td>
						
						<% if current_user != nil %>
							<% if current_user.roles == "Admin" %>
								<td><%= link_to "Comments",  show_comments_path(poi), 'data-no-turbolink' => true %></td>
								<td><%= link_to "Images",  show_unapproved_images_path(poi), 'data-no-turbolink' => true %></td>
								<td><%= link_to "Images",  show_approved_images_path(poi), 'data-no-turbolink' => true %></td>
							<% end %>
						<% end %>
						<td><%= link_to "Directions", "https://www.google.com/maps/dir/current%20%20location/#{poi.latitude},+#{poi.longitude}/@#{poi.latitude},#{poi.longitude},13z", :target => "_blank" %></td>
						<% if current_user != nil %>
							<% if current_user.roles == "Admin" %>
								<td><%= link_to 'Destroy', poi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							<% end %>
						<% end %>
					</tr>
				<% end %>
				</tbody>
			</table>
		</center>
	</div>
</div>

app/views/pois/show_users_pois.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<%= stylesheet_link_tag params[:controller] %>

<% if current_user.roles == "Admin" || current_user.roles == "Artist" %>

<div id="content_user_pois">
	<div id="user_pois">
		<center>
			<h2>Here is a list of all your POIs</h2>	
		</center>
		<hr><br />
		<center>
			<table border="2">
				<thead>
					<tr>
						<th>Image</th>
						<th>Title</th>
						<th>User</th>
						<th>User Uploaded</th>
						<th>Uploaded</th>
						<th>Show</th>
						<th>Edit</th>
						<th></th>
					</tr>
			    </thead>
	
				<tbody>
				<% @poi.each do |poi| %>
					<% if current_user.id == poi.user_id %>
						<tr>
							<% Poi.poi_home_image = false %>
							<% Dir.entries("public/images/#{poi.id}_images/title_image")[2..-1].each do |file_name| %>
								<% if file_name.byteslice(0,5).to_s.match(/_poi_/) %>
									<td><%= image_tag("#{@root_url}/images/#{poi.id}_images/title_image/" + file_name) %></td>
									<% Poi.poi_home_image = true %>
								<% end %>
							<% end %>
							
							<% if Poi.poi_home_image == false %>
								<td><img src="<%= @root_url %>/profile_images/no_profile_image.jpg" /></td>
							<% end %>
							
							<td><%= poi.title %></td>
							<td><%= link_to "Comments",  show_comments_path(poi), 'data-no-turbolink' => true %></td>
							<td><%= link_to "User Images",  show_approved_images_path(poi), 'data-no-turbolink' => true %></td>
							<td><%= link_to "Images",  show_images_path(poi), 'data-no-turbolink' => true %></td>
							<td><%= link_to "View", "/pois/#{poi.id}", 'data-no-turbolink' => true %></td>
							<td><%= link_to "Edit", "/pois/about/#{poi.id}", 'data-no-turbolink' => true %></td>
							<td><%= link_to 'Destroy', poi_path(poi), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
						</tr>
					<% end %>
				<% end %>
				</tbody>
			</table>
		</center>
		<br />
		<br />
		<center><h2>Here are just your wolves location on the map</h2></center>
		<hr>
		<center>
			<center><div id="user_map"></div></center>
			<script type="text/javascript">
			  function createSidebarLi(json){
				return ("<li><a>" + json.infowindow + "</a></li>");
			  };
			  
			  function bindLiToMarker($li, marker){
			    $li.on('click', function(){
			    	handler.getMap().setZoom(14);
			    	marker.setMap(handler.getMap()); //because clusterer removes map property from marker
			    	marker.panTo();
			    	google.maps.event.trigger(marker.getServiceObject(), 'click');
			  	})
			  };
			  function createSidebar(json_array){
				_.each(json_array, function(json){
					var $li = $( createSidebarLi(json) );
					$li.appendTo('#sidebar_container');
					bindLiToMarker($li, json.marker);
				});
			  };
			  
			  handler = Gmaps.build('Google');
			  handler.buildMap({ internal: {id: 'user_map'}}, function(){
			  	var json_array = <%=raw @hash.to_json %>;
				var markers = handler.addMarkers(json_array);
					
				_.each(json_array, function(json, index){
					json.marker = markers[index];
				});
					
				createSidebar(json_array);
				handler.bounds.extendWith(markers);
				handler.fitMapToBounds();
			  });
			</script>
		</center>
	</div>
</div>

<% else %>

<div id="content_user_pois">
	<div id="user_pois">
		<center>
			<h1>Sorry but you can not add a new poi without becoming an artist</h1>
		</center>
	</div>
</div>

<% end %>

app/views/pois/show_users_pois.mobile.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<%= stylesheet_link_tag "#{params[:controller]}.mobile" %>

<% if current_user.roles == "Admin" || current_user.roles == "Artist" %>

<div id="content_user_pois">
	<div id="user_pois">
		<center>
			<h2>Here is a list of all your POIs</h2>	
		</center>
		<hr><br />
		<center>
			<table border="2">
				<thead>
					<tr>
						<th>Image</th>
						<th>Title</th>
						<th>User</th>
						<th>User Uploaded</th>
						<th>Artist Uploaded</th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
			    </thead>
	
				<tbody>
				<% @poi.each do |poi| %>
					<% if current_user.id == poi.user_id %>
						<tr>
							<% Poi.poi_home_image = false %>
							<% Dir.entries("public/images/#{poi.id}_images/title_image")[2..-1].each do |file_name| %>
								<% if file_name.byteslice(0,5).to_s.match(/_poi_/) %>
									<td><%= image_tag("#{@root_url}/images/#{poi.id}_images/title_image/" + file_name) %></td>
									<% Poi.poi_home_image = true %>
								<% end %>
							<% end %>
							
							<% if Poi.poi_home_image == false %>
								<td><img src="#{@root_url}/images/profile_images/no_profile_image.jpg" /></td>
							<% end %>
							
							<td><%= poi.title %></td>
							<td><%= link_to "Comments",  show_comments_path(poi), 'data-no-turbolink' => true %></td>
							<td>
								<%= link_to "Unapproved Images",  show_unapproved_images_path(poi), 'data-no-turbolink' => true %><br />
								<%= link_to "Approved Images",  show_approved_images_path(poi), 'data-no-turbolink' => true %>
							</td>
							<td><%= link_to "Images",  show_images_path(poi), 'data-no-turbolink' => true %></td>
							<td><%= link_to "View", "/pois/#{poi.id}", 'data-no-turbolink' => true %></td>
							<td><%= link_to "Edit", "/pois/about/#{poi.id}", 'data-no-turbolink' => true %></td>
							<td><%= link_to 'Destroy', poi_path(poi), method: :delete, data: {confirm: 'Are you sure?' }, 'data-no-turbolink' => true %></td>
						</tr>
					<% end %>
				<% end %>
				</tbody>
			</table>
		</center>
		<br />
		<br />
		<center><h2>Here are just your wolves location on the map</h2></center>
		<hr>
		<center>
			<center><div id="user_map"></div></center>
			<script type="text/javascript">
			  function createSidebarLi(json){
				return ("<li><a>" + json.infowindow + "</a></li>");
			  };
			  
			  function bindLiToMarker($li, marker){
			    $li.on('click', function(){
			    	handler.getMap().setZoom(14);
			    	marker.setMap(handler.getMap()); //because clusterer removes map property from marker
			    	marker.panTo();
			    	google.maps.event.trigger(marker.getServiceObject(), 'click');
			  	})
			  };
			  function createSidebar(json_array){
				_.each(json_array, function(json){
					var $li = $( createSidebarLi(json) );
					$li.appendTo('#sidebar_container');
					bindLiToMarker($li, json.marker);
				});
			  };
			  
			  handler = Gmaps.build('Google');
			  handler.buildMap({ internal: {id: 'user_map'}}, function(){
			  	var json_array = <%=raw @hash.to_json %>;
				var markers = handler.addMarkers(json_array);
					
				_.each(json_array, function(json, index){
					json.marker = markers[index];
				});
					
				createSidebar(json_array);
				handler.bounds.extendWith(markers);
				handler.fitMapToBounds();
			  });
			</script>
		</center>
	</div>
</div>

<% else %>

<div id="content_user_pois">
	<div id="user_pois">
		<center>
			<h1>Sorry but you can not add a new poi without becoming an artist</h1>
		</center>
	</div>
</div>

<% end %>