config/routes.rb
Gmaps::Application.routes.draw do  
  resources :users
    get 'auth/:provider/callback', to: 'sessions#create_integration'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
	
  get "sessions/new"
	get "sessions/create"
	get "sessions/destroy"
  get "sessions/login"
  get "sessions/home"
  get "sessions/profile"
  get "sessions/logout"
  
  post "sessions/login"
  post "sessions/home"
  post "users/show"
  
  get "comment/index"
  
  get 'home', to: 'home#index'
  get 'show_all', to: 'pois#index'
  get 'join_in', to: 'users#new'
  get 'all_images', to: 'home#all_images'
  get 'sign_in', to: 'sessions#login'
  get 'all_managers', to: 'home#all_managers'
  
  get '/application/request_role/:id', to: 'application#request_role', as: 'request_role'
  post '/application/request_role/:id', to: 'application#request_role'
  patch '/application/request_role/:id', to: 'application#request_role'
  
  get '/users/edit_role/:id', to: 'users#edit_role', as: 'edit_user_role'
  get '/users/update_role/:id', to: 'users#update_role'
  post '/users/update_role/:id', to: 'users#update_role'
  patch '/users/update_role/:id', to: 'users#update_role'
  
  get '/pois/:id/show_images', to: 'pois#show_images', as: 'show_images'
  
  get 'sessions/forgot_password', to: 'sessions#forgot_password', as: 'forgot_password'
  put 'sessions/forgot_password', to: 'sessions#send_password_reset_instructions'
  
  post "sessions/send_password_reset_instructions"
  
  get "password_reset" => "sessions#password_reset"
  put "password_reset" => "sessions#new_password"
  
  get '/comments/poi_comments/:id', to: 'comments#poi_comments', as: 'show_comments'
  
  get '/pois/about/:id', to: 'pois#edit'
  patch '/pois/about/:id', to: 'pois#edit'
  put '/pois/about/:id', to: 'pois#edit'
  
  post '/pois/:id', to: 'pois#update'
  patch '/pois/:id', to: 'pois#upload_image'
  put '/pois/:id', to: 'pois#upload_image'
  
  patch '/users/:id', to: 'users#upload_profile_image'
  put '/users/:id', to: 'users#upload_profile_image'
  
	get "home/index"
	get "pois/index"
	get "pois/show_all"
  get '/pois/show_users_pois', to: 'pois#show_users_pois', as: 'show_users_pois'
  
  get 'pois/delete_image/:file_name', to: 'pois#delete_image', as: 'delete_image'
  get 'users/delete_profile_image/:file_name', to: 'users#delete_profile_image', as: 'delete_profile_image'
  
  get 'comments/destroy/:id', to: 'comments#destroy', as: 'remove_comment'
  delete 'comments/destroy/:id/:poi_id', to: 'comments#destroy', as: 'delete_comment'
  
  get '/users/approve/:id', to: 'users#approve', as: 'approve'
  get '/users/disapprove/:id', to: 'users#disapprove', as: 'disapprove'
  
  get '/comments/comment_images/:id', to: 'comments#unapproved_images', as: 'show_unapproved_images'
  get '/comments/approved_images/:id', to: 'comments#approved_images', as: 'show_approved_images'
  
  get '/comments/:id/approve/image/:file_name', to: 'comments#approve_image', as: 'approve_image'
  get '/comments/:id/disapprove/image/:file_name', to: 'comments#disapprove_image', as: 'disapprove_image'
  get '/comments/:id/delete_approved/image/:file_name', to: 'comments#delete_approved_image', as: 'delete_approved_image'
	
	get '/comments/user_upload_image'
	post '/comments/user_upload_image', to: 'comments#user_upload_image'
	
	post '/pois/:id/new_title_image', to: 'pois#new_title_image'
	patch '/pois/:id/new_title_image', to: 'pois#new_title_image'
	
	
	
	
  get 'messages/index', to: 'messages#index', as: 'inbox'
  get 'messages/new', to: 'messages#new', as: 'new_message'
  
  get 'messages/create'
  post 'messages/create', to: 'messages#create'
  
  delete 'messages/destroy/:id', to: 'messages#destroy', as: 'delete_message'
  
  get 'messages/show/:id', to: 'messages#show', as: 'show_message'
  
  get 'messages/sent', to: 'messages#sent', as: 'sent'
  
  get 'pois/update_rating/:id/:rating', to: "pois#update_rating", as: 'update_rating'
  post 'pois/update_rating/:id/:rating', to: "pois#update_rating"
	
	resources :pois
      resources :sessions, only: [:create, :destroy]
    resources :comments
	
	root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag("http://localhost:3000/favicon.jpg?1") %>
  <title>Wolf Point</title>
  <%= stylesheet_link_tag "application", "data-turbolinks-track" => true%>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script type="text/javascript">
var hh=0;
var inter;
function ShowBox()
{
     document.getElementById("behindText").style.display='none';
     if(hh==80){
         clearInterval(inter);
         return;
     }
     obj = document.getElementById("coverlogin");
     obj.style.visibility = 'visible';
     hh+=2;
     obj.style.height = hh + 'px';
     setTimeout('document.getElementById("closeMe").style.display=""',300);
}
  
function HideBox()
{
     obj = document.getElementById("coverlogin"); 
     if(hh==2){
         obj.style.visibility = 'hidden';
         obj.style.height = '0.1em';
         clearInterval(inter);
         return;
     }
 
     hh-=2;
     obj.style.height = hh + 'px';
     setTimeout('document.getElementById("closeMe").style.display="none"',300);
     setTimeout('document.getElementById("behindText").style.display=""',600);
}
</script>
</head>
<body>
<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<div id="top_bar">	
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>
    <% if current_user.roles == "Admin" %>
    <ul>
    	<li><%= link_to "See your profile", "/users/#{current_user.id}", 'data-no-turbolink' => true %></li>
    	<li><%= link_to "See all artist and users", "/users/", 'data-no-turbolink' => true %></li>
    <% else if current_user.roles == "Artist" %>
    <ul>
    	<li><%= link_to "See your profile", "/users/#{current_user.id}", 'data-no-turbolink' => true %></li>
    <% end %>
    <% end %>
    <% if current_user.roles == "Admin" || current_user.roles == "Artist" %>
	    	<li><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></li>
	    </ul>
    <% end %>
    <% if current_user.roles == "User" %>
	    	<li><%= link_to "Inbox", inbox_path, 'data-no-turbolink' => true %></li>
	    	<% if current_user.is_approved == false %>
	    		<li>Request Pending</li>
	    	<% else %>
	    		<li><%= link_to "Request Artist Account", request_role_path(current_user.id), method: :request_role, 'data-no-turbolink' => true %></li>
	    	<% end %>
	    </ul>
    <% end %>
    <%= link_to "Sign Out", "/sessions/logout", 'data-no-turbolink' => true %><br />
    <%= link_to 'Change Password', forgot_password_path %></td>
  <% else %>
    <div id="click_login">
	    <a href="#" ONCLICK="inter=setInterval('ShowBox()',3);return false;">Sign In</a> or <%= link_to " Join In", join_in_path, 'data-no-turbolink' => true %>
	</div>
	
	<div id="coverlogin">
	    <div id="loginbox">
	    	<form accept-charset="UTF-8" action="/sessions" method="post">
				<table>
					<tr>
						<td><label for="sessions_email">Email: </label>
						<input id="sessions_email" name="sessions[email]" type="text" />
						</td>
					</tr>
					<tr>
						<td><label for="sessions_password">Password: </label>
						<input id="sessions_password" name="sessions[password]" type="password" />
						</td>
					</tr>
					<tr>
						<td>
						<input class="btn btn-large btn-primary" name="commit" type="submit" value="Sign in" />
						<%= link_to "Go to Sign In page", sign_in_path, 'data-no-turbolink' => true %>
						</td>
					</tr>
				</table>
			</form>
	    </div>
	</div>
	
	<div id="behindText">
	</div>
	
  <% end %>
</div>

<div id="header">
	<div id="title_header">
		<img src="<%=@root_url%>/banner6.png">
	</div>
</div>

<% if current_user == nil%>
	<center>
		<div id="nav">
			<ul>
				<li><h3><%= link_to "Home", home_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Images of Wolves", all_images_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Artist", all_managers_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "Show All Wolves", show_all_path, 'data-no-turbolink' => true %></h3></li>
			</ul>
		</div>
	</center>
<% else if current_user.roles == "Artist" || current_user.roles == "Admin" %>
	<center>
		<div id="nav_roles">
			<ul>
				<li><h3><%= link_to "Home", home_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Images of Wolves", all_images_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Artist", all_managers_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "Show All Wolves", show_all_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "My Wolves", "/pois/show_users_pois", 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to 'New Wolf', new_poi_path, 'data-no-turbolink' => true %></h3></li>
			</ul>
		</div>
	</center>
<% else %>
	<center>
		<div id="nav">
			<ul>
				<li><h3><%= link_to "Home", home_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Images of Wolves", all_images_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Artist", all_managers_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "Show All Wolves", show_all_path, 'data-no-turbolink' => true %></h3></li>
			</ul>
		</div>
	</center>
<% end %>
<% end %>

<%= yield :scripts %>
<%= yield %>

<div id="footer">
	<h4><a href="https://bitbucket.org/kvaughn2/point-of-interest-capstone-group-l" target="_blank">Bitbucket Project Home Page</a></h4>
	<br />
	<h4><a href="https://bitbucket.org/kvaughn2/point-of-interest-capstone-group-l/wiki/Home" target="_blank">Wiki Home Page</a></h4>
	
</div>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag("http://localhost:3000/favicon.jpg?1") %>
  <title>Wolf Point</title>
  <%= stylesheet_link_tag "mobile", "data-turbolinks-track" => true%>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top_bar" >
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>
    <% if current_user.roles == "Admin" %>
    <%= link_to "See your profile", "/users/#{current_user.id}", 'data-no-turbolink' => true %> | <%= link_to "See all artist and users", "/users/", 'data-no-turbolink' => true %>
    <% else if current_user.roles == "Artist" %>
    <%= link_to "See your profile", "/users/#{current_user.id}", 'data-no-turbolink' => true %>
    <% end %>
    <% end %>
     | <%= link_to "Sign Out", "/sessions/logout", 'data-no-turbolink' => true %>
  <% else %>
    <%= link_to "Sign In", sign_in_path, 'data-no-turbolink' => true %>
    or
    <%= link_to " Join In", join_in_path, 'data-no-turbolink' => true %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<div id="header">
	<div id="title_header">
		<img src="<%=@root_url%>/banner6.png">
	</div>
</div>

<% if current_user == nil%>
	<center>
		<div id="nav">
				<li><h3><%= link_to "Home", home_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Images of Wolves", all_images_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Artist", all_managers_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "Show All Wolves", show_all_path, 'data-no-turbolink' => true %></h3></li>
		</div>
	</center>
<% else if current_user.roles == "Artist" || current_user.roles == "Admin" %>
	<center>
		<div id="nav_roles">
				<li><h3><%= link_to "Home", home_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Images of Wolves", all_images_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Artist", all_managers_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "Show All Wolves", show_all_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "My Wolves", "/pois/show_users_pois", 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to 'New Wolf', new_poi_path, 'data-no-turbolink' => true %></h3></li>
		</div>
	</center>
<% else %>
	<center>
		<div id="nav">
				<li><h3><%= link_to "Home", home_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "All Images of Wolves", all_images_path, 'data-no-turbolink' => true %></h3></li>
				<li><h3><%= link_to "Show All Wolves", show_all_path, 'data-no-turbolink' => true %></h3></li>
		</div>
	</center>
<% end %>
<% end %>

<%= yield %>
<%= yield :scripts %>

<div id="footer">
	
</div>

</body>
</html>